// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleUpload: typeof import('./components/ArticleUpload.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BreadCrumb: typeof import('./components/layouts/BreadCrumb.vue')['default']
    BytemdEditor: typeof import('./components/BytemdEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    MediaItem: typeof import('./components/MediaItem.vue')['default']
    MediaUpload: typeof import('./components/MediaUpload.vue')['default']
    NavBar: typeof import('./components/layouts/NavBar.vue')['default']
    Pagination: typeof import('./components/layouts/Pagination.vue')['default']
    SideBar: typeof import('./components/layouts/SideBar.vue')['default']
  }
}

export { }
